### ISSUE TITLE
Catalina Wine Mixer

### ISSUE THREAD

**Issue by isjodev** [Cthuloops/school#1]
Pow. 

Because there is no instant messaging feature on GitHub and this is easier than submitting a pull request from my cell phone.

**Comment by Cthuloops** [comment]
Lol are you going to come back to work?

**Comment by isjodev** [comment]
In another building for the time being. Shoot me an email with your cell #. 

i(dot)smith(dot)jackson(dot)o(at)gmail(dot)com
